<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDivisionParttimerTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('division_parttimer', function (Blueprint $table) {
            $table->unsignedInteger('division_id');
            $table->unsignedInteger('member_id');
            $table->nullableTimestamps();

            $table->primary(['division_id', 'member_id']);
            $table->index('division_id', 'division_parttimer_division_id_index');
            $table->index('member_id', 'division_parttimer_member_id_index');

            $table->foreign('division_id', 'division_parttimer_division_id_foreign')->references('id')->on('divisions')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->foreign('member_id', 'division_parttimer_member_id_foreign')->references('id')->on('members')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('division_parttimer');
    }
}
