<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLeavesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('leaves', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('member_id');
            $table->unsignedInteger('approver_id')->nullable();
            $table->unsignedInteger('requester_id');
            $table->enum('reason', ['military', 'medical', 'education', 'travel', 'other'])
                ->default('other');
            $table->unsignedInteger('note_id');
            $table->dateTime('end_date');
            $table->tinyInteger('extended')->nullable();
            $table->nullableTimestamps();

            $table->unique('member_id', 'leaves_member_id_unique');
            $table->index('approver_id', 'leaves_approver_id_index');
            $table->index('requester_id', 'leaves_requester_id_index');


        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('leaves');
    }
}
