<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateMembersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('members', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->unsignedMediumInteger('clan_id');
            $table->tinyInteger('rank_id')->default(1);
            $table->mediumInteger('platoon_id');
            $table->mediumInteger('squad_id');
            $table->tinyInteger('position_id')->default(1);
            $table->unsignedInteger('division_id');
            $table->string('ts_unique_id')->nullable();
            $table->tinyInteger('flagged_for_inactivity');
            $table->unsignedInteger('posts')->default(0);
            $table->timestamp('join_date')->nullable();
            $table->dateTime('last_activity')->nullable();
            $table->dateTime('last_ts_activity')->nullable();
            $table->dateTime('last_promoted_at')->nullable();
            $table->timestamp('last_trained_at')->nullable();
            $table->integer('last_trained_by')->nullable();
            $table->timestamp('xo_at')->nullable();
            $table->timestamp('co_at')->nullable();
            $table->integer('recruiter_id')->nullable();
            $table->softDeletes();
            $table->nullableTimestamps();

            

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('members');
    }
}
