<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateHandleMemberTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('handle_member', function (Blueprint $table) {
            $table->unsignedInteger('handle_id');
            $table->unsignedInteger('member_id');
            $table->string('value');
            $table->nullableTimestamps();

            $table->primary(['handle_id', 'member_id']);
            $table->index('handle_id', 'handle_member_handle_id_index');
            $table->index('member_id', 'handle_member_member_id_index');

            $table->foreign('handle_id', 'handle_member_handle_id_foreign')->references('id')->on('handles')->onDelete('CASCADE
')->onUpdate('RESTRICT');
            $table->foreign('member_id', 'handle_member_member_id_foreign')->references('id')->on('members')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('handle_member');
    }
}
