<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateActivitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('activities', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('subject_id');
            $table->string('subject_type');
            $table->string('name');
            $table->integer('user_id');
            $table->integer('division_id');
            $table->nullableTimestamps();

            $table->index('subject_id', 'activities_subject_id_index');
            $table->index('subject_type', 'activities_subject_type_index');
            $table->index('user_id', 'activities_user_id_index');
            $table->index('division_id', 'activities_division_id_index');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('activities');
    }
}
