<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDivisionHandleTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('division_handle', function (Blueprint $table) {
            $table->unsignedInteger('division_id');
            $table->unsignedInteger('handle_id');
            $table->timestamps();

            $table->primary(['division_id', 'handle_id']);
            $table->index('division_id', 'division_handle_division_id_index');
            $table->index('handle_id', 'division_handle_handle_id_index');

            $table->foreign('division_id')->references('id')->on('divisions')->onDelete('CASCADE');
            $table->foreign('handle_id')->references('id')->on('handles')->onDelete('CASCADE');
        });


    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('division_handle');
    }
}
