<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDivisionPopulationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('division_populations', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('division_id');
            $table->integer('count');
            $table->nullableTimestamps();

            

            $table->foreign('division_id', 'division_populations_division_id_foreign')->references('id')->on('divisions')->onDelete('CASCADE
')->onUpdate('RESTRICT');

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('division_populations');
    }
}
