<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email');
            $table->tinyInteger('role_id')->default(1);
            $table->mediumInteger('member_id');
            $table->text('settings');
            $table->tinyInteger('developer')->default(0);
            $table->rememberToken();
            $table->nullableTimestamps();
            $table->dateTime('last_login_at')->nullable();

            $table->unique('name', 'users_name_unique');
            $table->unique('email', 'users_email_unique');
            $table->unique('member_id', 'users_member_id_unique');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
