name: Tracker test suite

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  laravel-tests:

    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php7.4 -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
          php --version
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_API_USER }}" "${{ secrets.NOVA_API_KEY }}"
          composer install -n --prefer-dist

      - name: Generate key
        run: php7.4 artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1

      - name: Run Tests
        run: ./vendor/bin/phpunit --colors=always

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_ADMIN_WEBHOOK }}
